[package]
name = "Streamlet_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
chrono = "0.4.38"
tokio = { version = "1.40.0", features = ["time", "rt", "rt-multi-thread", "macros", "net", "sync", "io-util"] }
time = "0.3.36"
rand = "0.9.0-alpha.2"
serde_json = "1.0.128"
sha1 = "0.11.0-pre.4"
ring = "0.17.8"
base64 = "0.22.1"
toml = "0.8.19"