[package]
name = "Streamlet_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
chrono = "0.4.38"
tokio = { version = "1.40.0", features = ["time", "rt", "rt-multi-thread", "macros"] }
